### ISSUE TITLE
 www and others domain names

### ISSUE THREAD

**Issue by alesimancas** [WengerK/alejandra-chevey#54]
:(    <img width="1417" alt="screen shot 2018-03-16 at 01 34 38" src="https://user-images.githubusercontent.com/17951774/37498016-0c554f9e-28bc-11e8-9526-5f640a88a159.png">

**Comment by WengerK** [comment]
For me it works : 
- http://www.alechevey.ch
- http://alechevey.ch
- http://alejandra-chevey.com
- http://www.alejandra-chevey.com

It's the SSL which is not working as mentionned in  #52

**Comment by WengerK** [comment]
done 👍
