### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by WengerK** [WengerK/alejandra-chevey#56]
Something such as: https://gohugo.io/templates/404/

Need design before implementation, it will all be done in the following PR: #57

**Comment by alesimancas** [comment]
text: error: Wrong page my friend!

text travolta -Uh oh! It looks like you’re lost, go back to home

![source](https://user-images.githubusercontent.com/17951774/37874089-e32712ce-3027-11e8-8aea-b821e34bcc82.gif)
![source](https://user-images.githubusercontent.com/17951774/37874090-e6b324c8-3027-11e8-964e-bff8fc06b7cf.gif)

[error.webp.zip](https://github.com/WengerK/alejandra-chevey/files/1845190/error.webp.zip)
