### ISSUE TITLE
remove unused files 

### ISSUE THREAD

**Issue by alesimancas** [WengerK/alejandra-chevey#66]
Please remove unused files on alejandra-chevey/themes/alejandra-chevey/assets/images/
-resume
-alejandra.jpg

**Comment by alesimancas** [comment]
Remove unused files alejandra-chevey/themes/alejandra-chevey/assets/images/
Please erase all files more than 1y old.

@WengerK

**Comment by WengerK** [comment]
Can you list them or remove them in a PR ?
